"use client";

import { useEffect, useState } from "react";
import { Bar } from "react-chartjs-2";
import { BarElement, CategoryScale, Chart as ChartJS, Legend, LinearScale, Tooltip, type ChartOptions } from "chart.js";
import type { CsTeamPerformanceResult } from "@/lib/cs-performance";
import { formatChartDateLabel } from "@/lib/analytics-chart-theme";
import { formatRupiah } from "@/lib/gold-api";
import type { AnalyticsRange } from "./OperationalAnalytics";
import { AnalyticsEmptyState, AnalyticsKpiCard, AnalyticsPanel, AnalyticsSkeleton, ChartInsight, chartColors, StatusBadge, SummaryStrip } from "./AnalyticsUI";

ChartJS.register(CategoryScale, LinearScale, BarElement, Tooltip, Legend);

type TeamResponse = { data: CsTeamPerformanceResult };
type Member = CsTeamPerformanceResult["members"][number];
const tooltip = { backgroundColor: "#fffdf8", titleColor: chartColors.ink, bodyColor: chartColors.muted, borderColor: "#e8e0cf", borderWidth: 1, padding: 13, cornerRadius: 8 } as const;
const trendOptions: ChartOptions<"bar"> = { responsive: true, maintainAspectRatio: false, interaction: { intersect: false, mode: "index" }, animation: { duration: 400 }, plugins: { legend: { position: "bottom", labels: { color: chartColors.muted, usePointStyle: true, boxWidth: 7, padding: 18 } }, tooltip: { ...tooltip, callbacks: { title: items => formatChartDateLabel(items[0]?.label ?? "") } } }, scales: { x: { stacked: true, border: { display: false }, grid: { display: false }, ticks: { color: chartColors.muted, maxRotation: 0, maxTicksLimit: 9, callback(_value, index) { return formatChartDateLabel(this.getLabelForValue(index)); } } }, y: { stacked: true, beginAtZero: true, border: { display: false }, grid: { color: chartColors.grid }, ticks: { color: chartColors.muted, precision: 0 } } } };
const rankOptions: ChartOptions<"bar"> = { responsive: true, maintainAspectRatio: false, indexAxis: "y", plugins: { legend: { display: false }, tooltip }, scales: { x: { beginAtZero: true, border: { display: false }, grid: { color: chartColors.grid }, ticks: { color: chartColors.muted, precision: 0 } }, y: { border: { display: false }, grid: { display: false }, ticks: { color: chartColors.muted } } } };

export default function CsTeamAnalytics({ range }: { range: AnalyticsRange }) {
  const [data, setData] = useState<CsTeamPerformanceResult | null>(null);
  const [selected, setSelected] = useState<Member | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const controller = new AbortController();
    fetch(`/api/admin/analytics/cs-performance?from=${range.from}&to=${range.to}&grain=${range.grain}`, { signal: controller.signal })
      .then(async response => { const body = await response.json(); if (!response.ok) throw new Error(response.status === 403 ? "Performa tim hanya dapat diakses oleh admin." : body.error || "Gagal memuat performa CS."); return body as TeamResponse; })
      .then(result => { setData(result.data); setError(""); setLoading(false); })
      .catch(fetchError => { if (fetchError.name !== "AbortError") { setError(fetchError.message); setLoading(false); } });
    return () => controller.abort();
  }, [range.from, range.grain, range.to]);

  useEffect(() => { if (!selected) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") setSelected(null); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [selected]);

  if (loading) return <AnalyticsSkeleton cards={4} />;
  if (error) return <div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-5 text-sm text-red-700">{error}</div>;
  if (!data) return null;
  const m = data.metrics;
  const activeMembers = data.members.filter(member => member.performance.metrics.totalOrders > 0);

  return <div className="space-y-4">
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AnalyticsKpiCard label="Total CS" value={m.totalCs.toLocaleString("id-ID")} note="Akun dengan role CS" tone="gold" /><AnalyticsKpiCard label="CS Aktif" value={m.activeCs.toLocaleString("id-ID")} note="Membuat order dalam periode" tone="green" /><AnalyticsKpiCard label="Order Selesai" value={m.completedOrders.toLocaleString("id-ID")} note="Dari seluruh CS" tone="gold" /><AnalyticsKpiCard label="Rata-rata per CS" value={m.averageCompletedPerActiveCs.toLocaleString("id-ID")} note="Order selesai per CS aktif" /></div>
    <SummaryStrip items={[{ label: "Order dibatalkan", value: m.cancelledOrders.toLocaleString("id-ID"), note: "Tidak masuk performa selesai" }, { label: "Order tanpa atribusi", value: m.unattributedOrders.toLocaleString("id-ID"), note: "Tidak memiliki created_by" }, { label: "Nilai transaksi selesai", value: formatRupiah(m.completedValue), note: "Bukan penghasilan pribadi CS" }]} />
    <div className="grid gap-4 xl:grid-cols-12"><AnalyticsPanel className="xl:col-span-7" height="h-80" eyebrow="Aktivitas tim" title="Tren Performa CS" subtitle="Order selesai dan dibatalkan dari seluruh anggota tim." insight={<ChartInsight label="CS aktif" value={`${m.activeCs}/${m.totalCs}`} tone="green" />}>{data.trend.length ? <Bar options={trendOptions} data={{ labels: data.trend.map(point => point.key), datasets: [{ label: "Selesai", data: data.trend.map(point => point.completed), backgroundColor: chartColors.green, borderRadius: 4, borderSkipped: false }, { label: "Dibatalkan", data: data.trend.map(point => point.cancelled), backgroundColor: "rgba(220, 38, 38, .72)", borderRadius: 4, borderSkipped: false }] }} /> : <AnalyticsEmptyState />}</AnalyticsPanel><AnalyticsPanel className="xl:col-span-5" height="h-80" title="Peringkat Aktivitas" subtitle="Diurutkan berdasarkan order selesai terbanyak." insight={<ChartInsight label="Teratas" value={activeMembers[0]?.email.split("@")[0] ?? "—"} tone="amber" />}>{activeMembers.length ? <Bar options={rankOptions} data={{ labels: activeMembers.slice(0, 10).map(member => member.email.split("@")[0]), datasets: [{ label: "Order selesai", data: activeMembers.slice(0, 10).map(member => member.performance.metrics.completedOrders), backgroundColor: activeMembers.slice(0, 10).map((_, index) => index === 0 ? chartColors.gold : `rgba(200, 145, 22, ${Math.max(.3, .72 - index * .07)})`), borderRadius: 5, barThickness: 17 }] }} /> : <AnalyticsEmptyState />}</AnalyticsPanel></div>
    <section className="overflow-hidden rounded-xl border border-border/60 bg-white"><div className="p-5"><h2 className="font-serif text-lg font-semibold text-text">Perbandingan Performa CS</h2><p className="mt-1 text-xs text-text-muted">Seluruh akun CS tetap ditampilkan, termasuk yang tidak aktif pada periode ini.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-surface/50 text-left text-xs font-semibold uppercase tracking-wider text-text-muted"><tr><th className="px-5 py-3">Peringkat</th><th className="px-4 py-3">CS</th><th className="px-4 py-3">Selesai</th><th className="px-4 py-3">Jual</th><th className="px-4 py-3">Buyback</th><th className="px-4 py-3">Batal</th><th className="px-4 py-3">Completion</th><th className="px-4 py-3">Nilai</th><th className="px-4 py-3">Order terakhir</th><th className="px-5 py-3">Detail</th></tr></thead><tbody className="divide-y divide-border/30">{data.members.map((member, index) => { const metric = member.performance.metrics; return <tr key={member.id}><td className="px-5 py-3.5 font-serif text-base tabular-nums text-gold-dark">#{index + 1}</td><td className="px-4 py-3.5"><span className="font-medium text-text">{member.email.split("@")[0]}</span><br /><span className="text-xs text-text-muted">{member.email}</span></td><td className="px-4 py-3 tabular-nums">{metric.completedOrders}</td><td className="px-4 py-3 tabular-nums">{metric.sellOrders}</td><td className="px-4 py-3 tabular-nums">{metric.buybackOrders}</td><td className="px-4 py-3 tabular-nums">{metric.cancelledOrders}</td><td className="px-4 py-3"><StatusBadge tone={metric.completionRate >= 80 ? "green" : metric.completionRate > 0 ? "amber" : "neutral"}>{metric.completionRate}%</StatusBadge></td><td className="px-4 py-3 tabular-nums">{formatRupiah(metric.completedValue)}</td><td className="px-4 py-3 tabular-nums text-text-muted">{member.lastOrderAt ? new Date(member.lastOrderAt).toLocaleDateString("id-ID", { timeZone: "Asia/Jakarta" }) : "—"}</td><td className="px-5 py-3"><button type="button" onClick={() => setSelected(member)} className="rounded-lg border border-gold/40 px-3 py-1.5 text-xs font-semibold text-gold-dark hover:bg-gold/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold/40">Lihat</button></td></tr>; })}</tbody></table></div></section>
    {selected && <MemberDetail member={selected} onClose={() => setSelected(null)} />}
  </div>;
}

function MemberDetail({ member, onClose }: { member: Member; onClose: () => void }) {
  const metric = member.performance.metrics;
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/50 p-4 backdrop-blur-sm" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><section role="dialog" aria-modal="true" aria-labelledby="cs-detail-title" className="max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-xl border border-border/60 bg-white shadow-lg"><header className="flex items-start justify-between gap-4 border-b border-border/40 p-5"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-gold-dark">Detail performa</p><h2 id="cs-detail-title" className="mt-1 font-serif text-xl font-semibold text-text">{member.email.split("@")[0]}</h2><p className="mt-1 text-xs text-text-muted">{member.email}</p></div><button type="button" onClick={onClose} aria-label="Tutup detail performa" className="flex h-9 w-9 items-center justify-center rounded-lg border border-border/60 text-text-muted hover:bg-surface">×</button></header><div className="space-y-4 p-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><AnalyticsKpiCard label="Order" value={metric.totalOrders} note="Seluruh status" tone="gold" /><AnalyticsKpiCard label="Selesai" value={metric.completedOrders} note="Order selesai" tone="green" /><AnalyticsKpiCard label="Dibatalkan" value={metric.cancelledOrders} note="Order dibatalkan" tone={metric.cancelledOrders ? "red" : "green"} /><AnalyticsKpiCard label="Completion" value={`${metric.completionRate}%`} note="Tingkat penyelesaian" /></div><div className="overflow-x-auto rounded-xl border border-border/60"><table className="w-full min-w-[680px] text-sm"><thead className="bg-surface/50 text-left text-xs font-semibold uppercase tracking-wider text-text-muted"><tr><th className="px-4 py-3">Tanggal</th><th className="px-4 py-3">Order</th><th className="px-4 py-3">Pelanggan</th><th className="px-4 py-3">Tipe</th><th className="px-4 py-3">Nilai</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-border/30">{member.performance.recentOrders.map(order => <tr key={order.id}><td className="px-4 py-3 text-text-muted">{new Date(order.created_at).toLocaleDateString("id-ID", { timeZone: "Asia/Jakarta" })}</td><td className="px-4 py-3 font-medium">{order.order_number}</td><td className="px-4 py-3">{order.customer_name}</td><td className="px-4 py-3">{order.type === "sell" ? "Jual" : "Buyback"}</td><td className="px-4 py-3 tabular-nums">{formatRupiah(order.total)}</td><td className="px-4 py-3"><StatusBadge tone={order.status === "completed" ? "green" : "red"}>{order.status === "completed" ? "Selesai" : "Dibatalkan"}</StatusBadge></td></tr>)}</tbody></table></div></div></section></div>;
}
